# Generated by Django 4.0.1 on 2022-01-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizer',
            name='mytext',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='summarizer',
            name='summarize',
            field=models.TextField(),
        ),
    ]
