# Generated by Django 4.0.1 on 2022-01-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_summarizer_mytext_alter_summarizer_summarize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizer',
            name='mytext',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='summarizer',
            name='summarize',
            field=models.CharField(max_length=1000000),
        ),
    ]
